In [1]:
from sympy import *
import numpy as np

In [8]:
a1 = np.array([2,5,0,6,8,10,6,7,5,7])
a2 = np.array([8,6,7,9,6,6,2,3,2,3])
print(3*a1*2*a2)

[ 96 180   0 324 288 360  72 126  60 126]


In [9]:
a1 = np.array([9,6,7,7,0,1,6,8,1,2])
a2 = np.array([0,2,2,6,7,8,8,3,1,8])
print(6*a1*5*a2)

[   0  360  420 1260    0  240 1440  720   30  480]


In [11]:
a1 = np.array([2,5,0,6,8,10,6,7,5,7])
a2 = np.array([8,6,7,9,6,6,2,3,2,3])
print(a1*a2)

[16 30  0 54 48 60 12 21 10 21]


In [12]:
a1 = np.array([9,6,7,7,0,1,6,8,1,2])
a2 = np.array([0,2,2,6,7,8,8,3,1,8])
print(a1*a2)

[ 0 12 14 42  0  8 48 24  1 16]


In [6]:
def transponirovanie(matrix):
    sizes = np.shape(matrix)
    new_matrix = np.zeros((sizes[1],sizes[0]))
    for i in range(sizes[0]):
        for j in range(sizes[1]):
            new_matrix[j][i] = matrix[i][j]
            
    return new_matrix

matrix = [[3,7,8,3,6],
         [2,5,9,4,13]]
print(transponirovanie(matrix))
matrix = [[2,1,7,4],
         [5,6,7,3],
         [9,8,2,12],
         [11,14,15,15]]
print(transponirovanie(matrix))

[[ 3.  2.]
 [ 7.  5.]
 [ 8.  9.]
 [ 3.  4.]
 [ 6. 13.]]
[[ 2.  5.  9. 11.]
 [ 1.  6.  8. 14.]
 [ 7.  7.  2. 15.]
 [ 4.  3. 12. 15.]]


In [28]:
a1, a2 = symbols('a1 a2')
MSE=0.25 * ((a1 + 2*a2 - 5)**2 +
           (5*a1 + 3*a2 - 6)**2 +
           (2*a1 + 4*a2 - 10)**2 +
           (3*a1 + 7*a2 - 8)**2)
MSEa1 = diff(MSE, a1)
MSEa2 = diff(MSE, a2)
grad_MSE = np.array([MSEa1,MSEa2])
print(MSEa1, MSEa2)

19.5*a1 + 23.0*a2 - 39.5 23.0*a1 + 39.0*a2 - 62.0


In [29]:
print(MSE.subs({a1:0, a2:0}))
print(grad_MSE[0].subs({a1:0, a2:0}), grad_MSE[1].subs({a1:0, a2:0}))

56.2500000000000
-39.5000000000000 -62.0000000000000


In [40]:
result = MSE.subs({a1:0, a2:0})
a = 0
b = 0
while result>=6.36:
    print('Следующий шаг')
    print(f'Градиент равен [{grad_MSE[0].subs({a1:a, a2:b})}, {grad_MSE[1].subs({a1:a, a2:b})}]')
    x = (-1) * grad_MSE[0].subs({a1:a, a2:b}) * 0.01
    y = (-1) * grad_MSE[1].subs({a1:a, a2:b}) * 0.01 
    a += x
    b += y
    print(f'Новые коэф-ты равны [{a}, {b}]')
    result = MSE.subs({a1:a, a2:b})
    print(f'Новое значение MSE равно {result}\n')        
print('Достигли необходимой точности')

Следующий шаг
Градиент равен [-39.5000000000000, -62.0000000000000]
Новые коэф-ты равны [0.395000000000000, 0.620000000000000]
Новое значение MSE равно 16.8572437500000

Следующий шаг
Градиент равен [-17.5375000000000, -28.7350000000000]
Новые коэф-ты равны [0.570375000000000, 0.907350000000000]
Новое значение MSE равно 8.59365482859375

Следующий шаг
Градиент равен [-7.50863750000000, -13.4947250000000]
Новые коэф-ты равны [0.645461375000000, 1.04229725000000]
Новое значение MSE равно 6.85191449679269

Следующий шаг
Градиент равен [-2.94066643750000, -6.50479562500000]
Новые коэф-ты равны [0.674868039375000, 1.10734520625000]
Новое значение MSE равно 6.47725148826285

Следующий шаг
Градиент равен [-0.871133488437501, -3.29157205062501]
Новые коэф-ты равны [0.683579374259375, 1.14026092675625]
Новое значение MSE равно 6.38978037646670

Следующий шаг
Градиент равен [0.0557991134515632, -1.80749824854063]
Новые коэф-ты равны [0.683021383124860, 1.15833590924166]
Новое значение MSE равно 